name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.7.1
      - name: Build and publish package
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
